### PR TITLE
Fix: Pip error installing mod_wsgi in venv in Windows

### PR DESCRIPTION
**Pull request by antoniovazquezblanco**
Fixes https://github.com/GrahamDumpleton/mod_wsgi/issues/506

How: In `setup.py` always use base_prefix when locating libs as it points to the python installation wheter in a venv or not.

### CODE REVIEW

**Comment by antoniovazquezblanco** [comment]
Done!

**Comment by antoniovazquezblanco** [comment]
Friendly ping :)

**Comment by bazhenov4job** [comment]
What is the directory to place this file?

**Comment by bazhenov4job** [comment]
Successfully applied this on my win10 x64 with pip 20.0.2 and python 3.7.3

**Comment by tschoch** [comment]
can someone tell me where to put the setup.py file or make those changes? Experience the same behavior

**Comment by bazhenov4job** [comment]
Download the source code for mod wsgi from Antonio Vazquez's mod_wsgi
branch, navigate to the folder and do pip install .

вт, 11 февр. 2020 г., 17:49 tschoch <notifications@github.com>:

**Comment by tschoch** [comment]
Successfully applied this on Windows Server 2016 x64 with pip 20.0.2 and python 3.8.1

**Comment by antoniovazquezblanco** [comment]
Merged in https://github.com/GrahamDumpleton/mod_wsgi/commit/ffbdfaa87834d0a23f4147ef74164170d4400f86

Should we close this?

**Comment by GrahamDumpleton** [comment]
Use mod_wsgi 4.7.1 or later.

Sorry, I made the change separately, forgetting about the PR and that could merge it.

**Comment by antoniovazquezblanco** [comment]
Thanks!

**Pull request closed without merging**
