### PR TITLE
Attempt at Python 3.10 compatibility

### PR DESCRIPTION
**Pull request by encukou**
Hello,
Here is a *draft* of the changes to compile on Python 3.10 without GCC warnings. See https://github.com/GrahamDumpleton/mod_wsgi/issues/687. Best viewed as individual commits.
HOWEVER, I did not test this at all – I don't know enough about Apache to get things up and running in the time I have, and I'm not too good coding on whiteboards. Please use the code as a suggestion only.

I hope this helps a bit; if not, sorry for the noise.

### CODE REVIEW

**Comment by GrahamDumpleton** [comment]
Thanks for the pointers by way of the PR. Two points.

First point is that for file reading, I will probably be looking at using the Apache Runtime library ``apr_file_*()` functions instead to ensure compatibility with Windows. Also, either use ``apr_stat()`` and/or ``apr_file_seek()`` to work out file size up front so can allocate one blob of memory, possibly against Apache memory pools rather than ``malloc()`` and ``realloc()``.

Second point is thread initialization. It worries me a bit if ``PyEval_InitThreads()`` has disappeared. If that now always occurs it may be okay, but if you have to do something else will need to work out what it is.

Amusingly, if thread initialization is always done now and it is not possible to run Python without thread support, this will eliminate one of the tricks uWSGI uses to appear at lot faster in benchmarks. It doesn't actually enable threading support by default, so if always on now, then uWSGI default performance will drop. :-)

Am a bit slammed with work stuff right now, but will try and dig into these issues more in coming days. Thanks.

**Comment by GrahamDumpleton** [comment]
Sorry for slow reply. Won't the changes made mean that Python 2.7 and possibly older Python 3.X versions will no longer be supported? Do you happen to know when the newer C APIs were introduced. Conditional compilation may be required to preserve existing code and use that for older Python versions.

**Comment by encukou** [comment]
All the API is available in Python 2.6:
* [`sysconfig.get_config_var`](https://docs.python.org/2.6/distutils/apiref.html#distutils.sysconfig.get_config_var)
* [`PyObject_CallObject`](https://docs.python.org/2.6/c-api/object.html#PyObject_CallObject)
* [`PyImport_AddModule`](https://docs.python.org/2.6/c-api/import.html#PyImport_AddModule)
* [`PyObject_CallMethod`](https://docs.python.org/2.6/c-api/object.html#PyObject_CallMethod)
* `PyBytes_AsString` ([`PyString_AsString`](https://docs.python.org/2.6/c-api/string.html#PyString_AsString); [all `PyString_` functions have `PyBytes_*` aliases](https://docs.python.org/2.6/c-api/string.html))
* [`Py_CompileString`](https://docs.python.org/2.6/c-api/veryhigh.html#Py_CompileString)
* [`PyImport_ExecCodeModuleEx`](https://docs.python.org/2.6/c-api/import.html#PyImport_ExecCodeModuleEx)
* [`PyObject_CallObject`](https://docs.python.org/2.6/c-api/object.html#PyObject_CallObject)

That would leave `PyEval_InitThreads`: before 3.7 is needs to be called, after 3.9 it must not. There's an `#ifdef` for it.

Or do you need to support Python 2.5 or 3.2? Those are harder to research & test nowadays.

**Comment by GrahamDumpleton** [comment]
Someone else provided me with a PR for a GitHub action which compiles mod_wsgi when pushed against all major Python versions still in use, plus Python 3.10. So going to merge this now. Will then see if can work out how can run some actual WSGI requests against mod_wsgi-express under GitHub actions. Thanks a lot for the help.

**Comment by GrahamDumpleton** [comment]
And it all builds. Party time.

* https://github.com/GrahamDumpleton/mod_wsgi/actions/runs/948356696

**Comment by GrahamDumpleton** [comment]
Crashes and burns with Python 2.7. Well, doesn't crash, but fails basic test so need to work out why now.

**Comment by GrahamDumpleton** [comment]
Could be my test file is Python 3.X only, but then even if that is the case, no Python traceback is now being generated as to why it failed to compile.

**Comment by GrahamDumpleton** [comment]
Fails because in Python 2.7 this fails.

```
    io_module = PyImport_AddModule("io");
    if (!io_module) {
        goto load_source_finally;
    }

    fileobject = PyObject_CallMethod(io_module, "open", "ss", filename, "rb");
```

Error is:

```
AttributeError: 'module' object has no attribute 'open'
```

As in "open()" method doesn't exist on "io" module when imported using C API, which is a bit weird.

Yet on command line Python with Python import it does exist.

```
Python 2.7.16 (default, May  8 2021, 11:48:02)
[GCC Apple LLVM 12.0.5 (clang-1205.0.19.59.6) [+internal-os, ptrauth-isa=deploy on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import io
>>> io.open
<built-in function open>
```

**Comment by GrahamDumpleton** [comment]
Also worried about removal of usage of ``wsgi_utf8_to_unicode_path()`` on Windows, not sure if Python will cover what that was doing. Certain log info was also removed, as well as the logging of the errors when a problem.

So that now will work as before for Windows, likely going to have to go back to opening as C FILE and read as raw data into Python string buffer presized to what is required.

**Comment by GrahamDumpleton** [comment]
May in part be blowing up because code used ``PyImport_AddModule()`` when should be ``PyImport_ImportModule()``. The first one returns a borrowed reference, not new reference, yet the code was doing a reference decrement meaning the module was being deleted.

**Comment by GrahamDumpleton** [comment]
Using ``PyImport_ImportModule()`` fixed the presenting problem on Python 2.7, but eventually that would likely have caused crashes on Python 2.7 and 3.X as well since would decrement module on every call. Have also added back logging which got dropped, plus moved some reference count decrements to after Python error details were logged to ensure the error details weren't cleared by anything.

For now haven't restored use of ``wsgi_utf8_to_unicode_path()`` but will instead need to make change that ensures keyword argument of ``encoding="utf-8"`` is passed to ``io.open()`` else it may use default encoding which could be wrong.

**Comment by GrahamDumpleton** [comment]
Actually no. That argument is for file contents encoding. Issue here is encoding of the filename.

**Comment by encukou** [comment]
Thank you very much for the clean-up, and sorry for the `PyImport_AddModule` misstep!

Yes; the file is opened in binary mode and Python handles the path – that should be correct on all platforms.

**Pull request merged**
