### PR TITLE
Python 3.12 Support

### PR DESCRIPTION
**Pull request by deckar01**
> In Python 3.12, distutils will no longer be installed by make install or any of the first-party distribution. Third-party redistributors should no longer include distutils in their bundles or repositories.

https://peps.python.org/pep-0632/

The final 3.12.0 release is scheduled for 2023-10-02.

https://peps.python.org/pep-0693/#schedule

This migration is namespace changes other than `distutils.sysconfig.get_python_lib(plat_specific=1, standard_lib=1)` being replaced with `sysconfig.get_path('platstdlib')`.

<details><summary>sysconfig.get_path reference</summary>

> sysconfig.get_path(name)
> Return an installation path corresponding to the path name

https://docs.python.org/3.12/library/sysconfig.html#sysconfig.get_path

> platstdlib: directory containing the standard Python library files that are platform-specific.

https://docs.python.org/3.12/library/sysconfig.html#installation-paths

</details>

I tested these changes against python 3.8.0 and 3.12.0rc3. I also tested against a home build of python and verified that `get_path` correctly resolved the home lib.

### CODE REVIEW

**Comment by deckar01** [comment]
@GrahamDumpleton The test workflow is currently only building against python3.9. The python matrix only drives the test runner. Setting up a build matrix to cover python 3.12 revealed that `setuptools` stopped being included in fresh python installs by default. I think it was a transient dependency of `pip` that got dropped.

https://github.com/deckar01/mod_wsgi/actions/runs/6279472468/job/17055229521

As far as I can tell python doesn't provide any tooling for installing the `build-system:requires` from `pyproject.toml`, which seems odd. Adding `pip install setuptools` to `package.sh` fixed the issue, but I feel like I might be unaware of some tooling that would avoid the duplicated dependency declaration.

https://github.com/deckar01/mod_wsgi/actions/runs/6280040482

I am going to take this back out of draft, since this fix is enough to get the documented build flow working. If you would like me to setup a build matrix in this PR or a separate one, just let me know.

**Comment by GrahamDumpleton** [comment]
Can you update tox.ini file to also try and run tests on Python 3.12.

The attempts to do things for Python 2.6 and 2.7 will likely need to be removed as GitHub actions no longer supports Python 2.X in runners. IOW. need to drop Python 2.X support. Will need to remove those entries from PyPi project data.

FWIW. I am not entirely confident mod_wsgi will work on Python 3.12. The changes to sub interpreters are significant enough that I suspect mod_wsgi will blow up somewhere as the GIL was being relied upon to protect access to global shared data across sub interpreters. Since that will no longer work as before there will be corruption of global data. Finding all the places where alternate locking mechanisms need to be added is going to be a lot of work and ensuring that changes don't result in deadlocks because of lock acquisition ordering, especially on older Python versions, will be tricky.

So I would not recommend using mod_wsgi with Python 3.12 and I possibly should add a notice explicitly saying that Python 3.12 is not supported at this time.

Anyway, thanks for trying to update things for Python 3.12.

**Comment by GrahamDumpleton** [comment]
Oh. Seems I already dropped Python 2.X a while ago in the GitHub actions workflow at least. Just not been a release since.

**Comment by deckar01** [comment]
> 3.12 ... sub interpreters ... GIL

> [PEP 684](https://peps.python.org/pep-0684/) introduces a per-interpreter [GIL](https://docs.python.org/3.12/glossary.html#term-global-interpreter-lock)... This is currently only available through the C-API...

https://docs.python.org/3.12/whatsnew/3.12.html#whatsnew312-pep684

> The existing C-API [Py_NewInterpreter()] for managing interpreters will preserve its current behavior, with new behavior exposed through new API [Py_NewInterpreterFromConfig()]. No other API or runtime behavior is meant to change, including compatibility with the stable ABI.

https://peps.python.org/pep-0684/#backwards-compatibility

**Comment by GrahamDumpleton** [comment]
Despite what the PEP says, I still don't trust it. 😅

**Comment by deckar01** [comment]
Since the tests don't cover the edge cases you are concerned about, maybe this could be a beta release with a note in the readme warning that testing is needed (and directing feedback to a place you can mute 😆). Someday 3.12 will be the oldest supported version. If there are bugs I would like to find them before the behavior has been carved into stone.

**Comment by GrahamDumpleton** [comment]
If you are able to, can you validate with: https://pypi.org/project/mod-wsgi/5.0.0rc1/

**Pull request merged**
