### PR TITLE
Use PyConfig API on Python 3.8

### PR DESCRIPTION
**Pull request by vstinner**
The following functions used by mod_wsgi are deprecated:

* PySys_AddWarnOption()
* Py_SetProgramName()
* Py_SetPythonHome()

Replace deprecated functions with the PyConfig API on Python 3.8. On error (usually memory allocation failure), log a critical message.

Replace:

* Py_OptimizeFlag: config.optimization_level
* PYTHONHASHSEED: config.use_hash_seed and config.hash_seed
* PySys_AddWarnOption(): PyWideStringList_Append(&config.warnoptions)
* Py_SetPythonHome(): PyConfig_SetString(&config.home)
* Py_SetProgramName(): PyConfig_SetString(&config.program_name)
* Py_Initialize(): Py_InitializeFromConfig()

The PYTHONHASHSEED environment variable is no longer set and so doesn't need to be unset later.

### CODE REVIEW

**Comment by vstinner** [comment]
I didn't run a functional test! I only validated my work using `tox --parallel auto`.

The problem is that PySys_AddWarnOption(), Py_SetProgramName() and Py_SetPythonHome() functions were removed in Python 3.13 alpha 1.

I'm considering to restore Py_SetProgramName() and Py_SetPythonHome() functions in incoming Python 3.13 beta 1: https://github.com/python/cpython/issues/117987 But mod_wsgi also uses PySys_AddWarnOption().

The PyConfig API is available since Python 3.8:

* API documentation: https://docs.python.org/dev/c-api/init_config.html
* Design PEP: https://peps.python.org/pep-0587/

**Comment by vstinner** [comment]
@GrahamDumpleton: Would you mind to have a look at this PR?

**Comment by GrahamDumpleton** [comment]
👍 Due to some work changes I finally have some time now, so will be catching up on both mod_wsgi and wrapt stuff in the coming weeks.

**Comment by GrahamDumpleton** [comment]
Without any of these changes Python 3.13.0-rc.2 seems to compile and work fine under GitHub actions workflow. Was the removal of all the C APIs mentioned abandoned?

**Comment by vstinner** [comment]
> Was the removal of all the C APIs mentioned abandoned?

Right, some deprecated functions were removed but then restored again since the removal broke too many projects.

**Comment by vstinner** [comment]
Thanks for the merge!

**Comment by GrahamDumpleton** [comment]
Version 5.0.1.rc1 is released on PyPi now if want to give that a try on Python 3.13.

**Comment by vstinner** [comment]
I can `tox -e py13` on commit 90bc175b8cf71b548f0a8da1986f4751a4a5a039 with Python 3.13.0rc2: tests pass successfully :-)

```
vstinner@mona$ tox -e py13
.pkg: _optional_hooks> python /home/vstinner/.local/lib/python3.12/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
.pkg: get_requires_for_build_sdist> python /home/vstinner/.local/lib/python3.12/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
.pkg: get_requires_for_build_wheel> python /home/vstinner/.local/lib/python3.12/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
.pkg: prepare_metadata_for_build_wheel> python /home/vstinner/.local/lib/python3.12/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
.pkg: build_sdist> python /home/vstinner/.local/lib/python3.12/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
py13: install_package> python -I -m pip install --force-reinstall --no-deps /home/vstinner/dev/mod_wsgi/.tox/.tmp/package/3/mod_wsgi-5.0.1rc1.tar.gz
  py13: OK (17.05 seconds)
  congratulations :) (17.11 seconds)
```

**Pull request merged**
