### PR TITLE
Support downloading large files

### PR DESCRIPTION
**Pull request by milos-u**
Patch based on https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=622730

### CODE REVIEW

**Comment by GrahamDumpleton** [comment]
I recollect more changes are required than that and why had been holding off. There was some issue around the wsgi.file_wrapper implementation as well. I will look over the code again to try and identify any other changes which may be required.

**Comment by GrahamDumpleton** [comment]
One change relates to the size of individual strings yielded from a WSGI application. It is unlikely anyway would yield a single string from a WSGI application more than 2GB size, but the limitation doesn't currently exist. Should fix that at the same time.

**Comment by milos-u** [comment]
I've tested the mod_wsgi with this patch in production and although I'm able to start the download of 3 GB file, after downloading cca 1GB of data, the download fails.
The behaviour is actually very similar to: https://groups.google.com/forum/#!topic/modwsgi/2lX8hARwN00
I will try to add an issue regarding this.

**Comment by GrahamDumpleton** [comment]
I have superseded this with #4e757103334765691fab24362a41c870c990be8f which deals with some other issues with type/size of variables used to track content length. Can you try 'develop' branch and see how it works for you?

**Comment by milos-u** [comment]
Downloading large (10GB) file with https://github.com/GrahamDumpleton/mod_wsgi/commit/4e757103334765691fab24362a41c870c990be8f works. No problem.

Apache/2.4.12 (Win32) OpenSSL/1.0.1l mod_wsgi/4.5.10 Python/2.7.11 running on Windows Server 2012 R2.

**Comment by GrahamDumpleton** [comment]
Was released in 4.5.10.

**Pull request closed without merging**
