### PR TITLE
Static analysis warning fixes

### PR DESCRIPTION
**Pull request by notroj**
A set of commits with hopefully uncontroversial fixes for warnings from both GCC and Coverity scanning.

### CODE REVIEW

**Comment by notroj** [comment]
Another one in wsgi_publish_event which looks a valid warning but I am not sure how best to resolve:

In the `if (module)` path, list is assigned and assumed to be non-NULL if module is non-NULL:

```
        list = PyDict_GetItemString(dict, "event_callbacks");

        Py_INCREF(list);
```

in the `module == NULL` path, the branch returns.

The following lines have:

```
    if (!list) {
        Py_BEGIN_ALLOW_THREADS
        ap_log_error(APLOG_MARK, APLOG_ERR, 0, wsgi_server,
                     "mod_wsgi (pid=%d): Unable to find event subscribers.",
                     getpid());
```

if we really need to allow for `list == NULL` should the earlier `Py_INCREF(list)` be changed to `Py_XINCREF(list)`?

**Comment by notroj** [comment]
@GrahamDumpleton anything I can do to help get this merged?

**Comment by GrahamDumpleton** [comment]
Sorry, completely overlooked it. I will try and look at it in the next few days, but a glance suggests a number of things are not valid and would actually remove functionality. So I don't believe it can be merged as is.

**Comment by GrahamDumpleton** [comment]
I have gone through and manually applied those that could, and used the opportunity to clean up the code which you flagged for deletion, but which would have resulted in functionality being removed. The latter warnings were because I hadn't decided whether to enable a feature or not, and so the usage of the variable was within blocked out code. The problem was that the call of the function, the result of which was assigned to the variable, had to be done either way, it wasn't optional, whether or not anything was done with the result. Changes in `develop` branch, but should make release real soon.

**Pull request closed without merging**
