### PR TITLE
Implement support for Apache mod_session module

### PR DESCRIPTION
**Pull request by mathieubouchard**
This commit add hooks to mod_wsgi so it can be configured to be a provider to mod_session. This implements all 4 methods listed in Issue #185 of the old bug tracker (https://code.google.com/p/modwsgi/issues/detail?id=185).

If you look at the diff, you will see a lot of modifications on wsgi_hook_check_user_id. In reality, I didn't touch this method. The problem occurred because I reused a lot of the code used to call a python method.

I used the 4 new hooks to secure a web server that runs multiple applications, with one Django app. I wanted the users to use a Django form to log in instead of a browser pop-up. I used mod_auth_form and didn't want to stock the username / password values into an encrypted cookie or database. Since the mod is dependant on a very strict session support, I had to simulate an authentication with a username / password (in reality, I'm using the Django session cookie to authenticate the users).

The Apache config I used is :

```
    WSGIScriptAlias /app /home/user/myapp/app.wsgi
    WSGIScriptAlias /otherapp /home/user/otherapp/app.wsgi
    ProxyPass /javaapp http://localhost:8080/java
    [...]

    <Location />
        AuthType Form
        AuthFormProvider wsgi
        AuthName "APP"
        AuthFormLoginRequiredLocation /app/accounts/login/?next=%{REQUEST_URI}
        WSGIAuthUserScript /home/user/myapp/auth.wsgi
        Session On
        WSGISessionScript /home/user/myapp/auth.wsgi
        Require valid-user
    </Location>

    <Location /app/accounts/login>
        Require all granted
    </Location>
```

Here's a description of the four python methods that must be created to support sessions :
1. _load_session_ : Receives an AuthObject. Returns a string (the encoded session). A value of None means there is no saved session.
2. _decode_session_ : Receives an AuthObject and a string (the encoded session). Returns a dictionary of strings as key / values (no other types are supported). A return value of None means an Error.
3. _encode_session_ : Receives an AuthObject and a dictionary of strings as key / values. Returns either a string (the encoded session) or None if the hook must be DECLINED.
4. _save_session_ : Receives an AuthObject and a string (the encoded session). Returns either True if the session was saved successfully, False if there was an error or None if the hook must be DECLINED.

Full example (django implementation) :

```
# -*- coding: utf-8 -*-

import sys
import os

APACHE_AUTH_KEY = u"AUTH_NAME"
APACHE_USER_KEY = u"user"
APACHE_PASS_KEY = u"pw"

sys.path.insert(0, os.path.dirname(__file__))
os.environ['DJANGO_SETTINGS_MODULE'] = 'myapp.settings'

def __get_apache_keys_(environ):
    user_key = APACHE_USER_KEY
    pw_key = APACHE_PASS_KEY
    if APACHE_AUTH_KEY in environ:
        authname = environ[APACHE_AUTH_KEY]
        if authname is not None:
            user_key = authname + u"-" + user_key
            pw_key = authname + u"-" + pw_key

    return (user_key, pw_key)

def __get_session_id_(environ):
    from django.conf import settings
    from django.http import parse_cookie

    if u"HTTP_COOKIE" in environ:
        cookies = parse_cookie(environ[u"HTTP_COOKIE"])
        if settings.SESSION_COOKIE_NAME in cookies:
            return cookies[settings.SESSION_COOKIE_NAME]

def __get_session_(environ):
    from django.contrib.sessions.models import Session

    s = None

    session_id = __get_session_id_(environ)
    if session_id is not None:
        try:
            s = Session.objects.get(pk = session_id)
        except Session.DoesNotExists:
            pass

    return s

def __encode_data_(data):
    from importlib import import_module
    from django.conf import settings

    SessionStore = import_module(settings.SESSION_ENGINE).SessionStore
    s = SessionStore()
    return s.encode(data)

def __decode_data_(data):
    from importlib import import_module
    from django.conf import settings

    SessionStore = import_module(settings.SESSION_ENGINE).SessionStore
    s = SessionStore()
    return s.decode(data)

def check_password(environ, username, password):
    s = __get_session_(environ)
    session_data = s.get_decoded()

    from django.contrib.auth import SESSION_KEY
    if SESSION_KEY in session_data and session_data[SESSION_KEY] is not None:
        from django.contrib.auth import get_user_model
        UserModel = get_user_model()

        try:
            user = UserModel.objects.get(pk = session_data[SESSION_KEY])
            return True
        except UserModel.DoesNotExist:
            pass

    return False

def load_session(environ):
    s = __get_session_(environ)
    if s is not None:
        return s.session_data

def decode_session(environ, data):
    session_data = __decode_data_(data)

    (user_key, pw_key) = __get_apache_keys_(environ)
    if user_key not in session_data:
        from django.contrib.auth import SESSION_KEY
        from django.contrib.auth import get_user_model
        UserModel = get_user_model()

        user = None
        if SESSION_KEY in session_data:
            uid = session_data[SESSION_KEY]
            if uid is not None:
                try:
                    user = UserModel.objects.get(pk = uid)
                except UserModel.DoesNotExist:
                    pass

        if user is not None:
            session_data[user_key] = user.get_username()
            if pw_key not in session_data:
                session_data[pw_key] = u"<fake>"

    return {k.encode(u"utf-8"):v.encode(u"utf-8") for (k,v) in session_data.iteritems() if no$

def encode_session(environ, data):
    (user_key, pw_key) = __get_apache_keys_(environ)
    if user_key in data:
        del data[user_key]
    if pw_key in data:
        del data[pw_key]

    s = __get_session_(environ)
    session_data = __decode_data_(s.session_data)
    for key in data:
        if not key.startswith(u"_"):
            session_data[key] = data[key]

    return __encode_data_(session_data)

def save_session(environ, data):
    s = __get_session_(environ)
    if s is not None:
        s.session_data = data
        s.save()
        return True

    return False
```

To avoid overriding django values, we can also ignore session saving :

```
def encode_session(environ, data):
    pass

def save_session(environ, data):
    pass
```

### CODE REVIEW

**Comment by Bengreen** [comment]
was this modification completed and integrated OR is there an alternative way to achieve this?

**Comment by GrahamDumpleton** [comment]
The PR as it existed couldn't be merged as it would cause problems for various reasons. I started on refactoring of the mod_wsgi code base such that it was possible to generate two Apache modules, as the session provider needed to be separate, but got side tracked and never finished the work. The git stash I have it in is now out of date with the code base and would need to start over.

The question of ``mod_session`` integration did come up again recently due to a question asked of me via work, and I did think again about this stuff and whether should try again at adding support, but it is a considerable amount of work to do the necessary refactoring, so not sure when I would be able to get to it.

As to alternatives to integrating a session provider which uses Python I can't say I know for sure. I though there was a way by offloading authentication off to any handler and communicating back and forth via headers, or CGI script at worst, but can't find it now. Only other option is to use ``mod_authn_dbd`` and go direct to your database which is managed by the Python web application.

So question is really what session provider backend do you want to hook into?

**Comment by Bengreen** [comment]
The scenario I am aiming to create is as follows:
I want to use Apache to implement the routing of multiple applications some of which are run on the same server, some of which are proxy pass through.
I want to use apache to authenticate users on these applications so that it can stop access if the user is not logged in and redirect to login. I am using 'AuthType Form' and 'AuthFormProvider wsgi' to provide this and have a small python that will do the auth against the backed which could be multiple different types of authentication mechanism depending on the particular configuration... BUT all will go through flask and postres.
My login process will be through Flask. And i will extend the currently small python method to use the authentication process within my flask application.

i aim to use form based login to login to the server which generates an apache cookie for me which i am using for ensuring login for the different apps.

Currently i have a small test/demo where I use a form handler to create the login session cookie, but will upgrade this to use wsgi/flask to allow it to create the auth session cookie in the future.

So I am trying to work out how to get wsgi/flask to write the cookie with an Apache friendly cookie (hoping these APIs will help me here) that way I can use one cookie for both my flask app and apache (I am also aiming to use SessionCryptoPassphrase here as well) SO i am assuming that these api consider the encrypt/decrypt functions already.
OR i create two cookies. One for apache session management and a separate for flask/wsgi session management and then i have the wsgi/flask look after the creation and deleting of both cookies simultaneously.

Any hints would be very useful.

I am happy to invest some time in this if there is a good clean way that it should be done.

**Comment by GrahamDumpleton** [comment]
Cleaning up old stuff laying around. Going to close this out. As far as the life of mod_wsgi goes such a change is probably way too late to consider since mod_wsgi is more or less in maintenance mode, or at least only minor changes are being made. The changes to support mod_session is too much and only a few people have ever been interested in the capability.

**Pull request closed without merging**
